//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangtonAnt.Res.Str {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrResxBackendIn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrResxBackendIn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LangtonAnt.Res.Str.StrResxBackendIn", typeof(StrResxBackendIn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Steps:.
        /// </summary>
        internal static string DisplayCountSteps {
            get {
                return ResourceManager.GetString("DisplayCountSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Size:.
        /// </summary>
        internal static string DisplayGridSize {
            get {
                return ResourceManager.GetString("DisplayGridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string DisplayStartBtn {
            get {
                return ResourceManager.GetString("DisplayStartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant Start Direction:.
        /// </summary>
        internal static string DisplayStartDirectionAnt {
            get {
                return ResourceManager.GetString("DisplayStartDirectionAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ant Start Position:.
        /// </summary>
        internal static string DisplayStartPosAnt {
            get {
                return ResourceManager.GetString("DisplayStartPosAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:.
        /// </summary>
        internal static string DisplayStartPosXAnt {
            get {
                return ResourceManager.GetString("DisplayStartPosXAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y:.
        /// </summary>
        internal static string DisplayStartPosYAnt {
            get {
                return ResourceManager.GetString("DisplayStartPosYAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ant Start Position X..
        /// </summary>
        internal static string ErrMsgInvalidAntStartPosX {
            get {
                return ResourceManager.GetString("ErrMsgInvalidAntStartPosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ant Start Position Y..
        /// </summary>
        internal static string ErrMsgInvalidAntStartPosY {
            get {
                return ResourceManager.GetString("ErrMsgInvalidAntStartPosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number of Steps..
        /// </summary>
        internal static string ErrMsgInvalidCountSteps {
            get {
                return ResourceManager.GetString("ErrMsgInvalidCountSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Grid Size..
        /// </summary>
        internal static string ErrMsgInvalidGridSize {
            get {
                return ResourceManager.GetString("ErrMsgInvalidGridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langton&apos;s ant.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
